### ISSUE TITLE
covs option implementation

### ISSUE THREAD

**Issue by vpolkovn** [rdpackages/rdrobust#1]
The guide "A Practical ...." Cattaneo, Idboro, Titiuinik (2019) states that covariates included as a common linear function on both left and right side with coefficient gamma (equation 4.3 on p. 79). 
However running R snippet 26 on p.83 reports more than one common coefficient. When covs option is used there are two two sets of coefficients returned for each covariate in beta_p_r and beta_p_l and the dimension of coefficients is p+1. This is inconsistent with the guide and it is unclear in what way covariates are incorporated.

**Comment by mdcattaneo** [comment]
Hi, thanks for your question. Please note that there are different sets of coefficients: those related to the running variable (which are not restricted), and those related to the additional covariates (which are restricted to be equal below and above the cutoff). More details are here: https://rdpackages.github.io/references/Calonico-Cattaneo-Farrell-Titiunik_2019_RESTAT.pdf

**Comment by vpolkovn** [comment]
Hi Matias thanks for your quick response. I checked the output out$beta_p_l and out$beta_p_r and they are 1) different for covs on left and right sides 2) they are order p+1 while there should be only one set of gamma on Z.
It is not clear how the covs option is incorporated. If its linear with single restricted coefficient on both sides then why these outputs are different and have order p+1. Before I got your response I have posted it with details of code and output in stackoverflow here:
https://stackoverflow.com/questions/66754072/rdrobust-package-with-covariates-returns-too-many-coefficients

**Comment by mdcattaneo** [comment]
Hi again. The model fitted is given in equation (2) of Calonico, Cattaneo, Farrell & Titiunik (2019, RESTAT). For be very explicit:

-- \beta_- corresponds to the p+1 coefficients on the running variable below the cutoff.
-- \beta_+ corresponds to the p+1 coefficients on the running variable above the cutoff.
-- gamma corresponds to the d coefficients for the additional covariates (restricted to be equal below and above the cutoff).

The total number of coefficients estimated (via local polynomial methods) for point estimation is: 2*(p+1) + d.

Please take a look at this paper: https://rdpackages.github.io/references/Calonico-Cattaneo-Farrell-Titiunik_2019_RESTAT.pdf -- It explains the exact rational of why we restrict the gamma coefficients on the additional covariates. Finally, in answering you generic question: our model is (locally to the cutoff) additive separable in the running variable (X) and the other covariates (Z).

Hope this helps!

**Comment by vpolkovn** [comment]
Thank you, yes this is exactly how I understood it. gamma is restricted to be equal and equation is linear in Z. But when running with p=1 and covs =Z with dim(Z)=7 there are returned many more coefficients with total of 2*(p+1) + 2*(p+1)*d. Please see the actual output in the stackoverflow link I gave above.

**Comment by vpolkovn** [comment]
Matias thanks for the responses. This is exactly how I understood it. But the output returned is 2*(p+1)+2*(p+1)*d
Thanks!
Valery

Here is the screen shot:

***@***.***D71F46.B85292B0]

**Comment by mdcattaneo** [comment]
Hi once more. We now understand what your question was about, namely what we report as output in RDROBUST when covariates are included. We checked our output and, yes, you are correct to point out that we report extra information. In particular, we report the beta coefficients corresponding to Y on X (adjusting for Z) and also the coefficients corresponding to Z on X (that is, the rdrobust estimate for each Z on X). This means we report (1+d) rdrobust regressions, each of which gives (p+1) coefficients. Hence, we arrange the output in a matrix of (p+1)x(1+d) dimension. To address this confusion, we will update RDROBUST this week and remove the additional coefficients corresponding to Z on X, so the new output will always be that of Y on X, regardless of whether one added covariates. Please update RDROBUST later this week, and do let us know if there is anything confusing still. Cheers, Matias

**Comment by vpolkovn** [comment]
Hi Matias, many thanks for your clarification. It makes sense now. In fact I would suggest that you keep this information and simply update the description of output in the packages. I think many researchers, myself including, would find it useful to have additional diagnostics. And may be also add gamma coefficient on covariates to the output? That is how I started looking into detailed output trying to find gamma but could not find it. For now I have to add it manually modifying installed package code. Best, Valery

**Comment by mdcattaneo** [comment]
Hi Valery: we are in the process of putting together a new package that will do covariate adjustment when changing the estimand. This requires some additional work. Once we have this completed, we will provide the additional gammas along with proper statistical inference methods. I will go ahead and close this thread and delete it, as it is not general interest. Thanks! Matias
